name: deployment

on:
  release:
    types: [published]
    tags:
      - release-*

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1

      - name: package install
        run: npm ci

      - name: build
        run: npm run build
        env:
          app_env: prod

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # - name: deploy
      #   run: npm run deploy
